### ISSUE TITLE
Custom Toggle switch component

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#3569]
The currently package `vue-js-toggle-button` is not reactively toggling the switch. For instance:

```js
commitFeature: {
    get: function() {
        return !!+this.settings.commitFeature;
    },
    set: function(value) {
        this.settings.commitFeature = value ? 1 : 0;
    }
}
```

**Comment by rampreeth** [comment]
Taking a look at this.

**Comment by rampreeth** [comment]
I am facing an issue while trying to set it up locally.

**Comment by mittalyashu** [comment]
May I know what kind of issue are you facing? @rampreeth

**Comment by rampreeth** [comment]
<pre>
yarn
yarn install v1.19.0
warning package.json: License should be a valid SPDX license expression
warning thermal@0.0.4: License should be a valid SPDX license expression
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[-/4] ⠠ waiting...
[2/4] ⠠ fsevents
[3/4] ⠠ electron
error /Users/rampreeth.ethiraj/open-source-repos/src/thermal/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/rampreeth.ethiraj/open-source-repos/src/thermal/node_modules/electron
Output:
Downloading tmp-7905-0-electron-v5.0.6-darwin-x64.zip
Error: connect ETIMEDOUT 13.234.210.38:443
/Users/rampreeth.ethiraj/open-source-repos/src/thermal/node_modules/electron/install.js:49
  throw err
  ^

Error: connect ETIMEDOUT 13.234.210.38:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '13.234.210.38',



warning Error running install script for optional dependency: "/Users/rampreeth.ethiraj/open-source-repos/src/thermal/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/rampreeth.ethiraj/open-source-repos/src/thermal/node_modules/fsevents
Output:
</pre>

Looks like it is failing when it is trying to install electron.

**Comment by mittalyashu** [comment]
@rampreeth Seems like the issue is not related to electron instead it's because of the connection timeout.

```
Error: connect ETIMEDOUT 13.234.210.38:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '13.234.210.38',
```

**Comment by mittalyashu** [comment]
Wanted to check on the progress for the component @rampreeth.

**Comment by rampreeth** [comment]
Yes so I think the issue is with reactivity in vue. We need to probably use this.$set. I'm yet to try that out.

**Comment by mittalyashu** [comment]
Are you trying to fix an exiting toggle switch or creating a new one?

**Comment by rampreeth** [comment]
Existing one itself.

**Comment by mittalyashu** [comment]
> Existing one itself.

No no, seems like you miss-understood the issue title.

You need to create a custom toggle switch component @rampreeth

**Comment by rampreeth** [comment]
As per the issue , the existing toggle component is not working right. I think that is happening because of vue reactivity.

**Comment by mittalyashu** [comment]
Yes, I am aware of that problem, that's why I have created this issue to create a new custom toggle switch component.

**Comment by mittalyashu** [comment]
@rampreeth did you make any progress in creating custom toggle switch component?
